window:
  padding: 
    x: 10
    y: 10
  opacity: 0.7

scrolling:
  history: 1000

font:
  normal:
    family: 'Hack Nerd Font Mono'  
  size: 10.0

colors:
  primary:
    background: '#282C34'
    foreground: '#ABB2BF'

live_config_reload: true
