#!/bin/sh

##### AUTO START ######
~/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom.conf &
feh --bg-fil ~/Pictures/wallpaper-onedark.webp &
xsetroot -cursor_name left_ptr
xfce4-power-manager &

##### BSPWM Config #####
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0 

bspc config border_width                  1
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                10
bspc config left_padding                  10
bspc config right_padding                 10 

bspc config focus_follows_pointer         true

bspc config normal_border_color		  "#ABB2BF"
bspc config active_border_color	          "#C678DD"
bspc config focused_border_color	  "#C678DD"
bspc config presel_feedback_color	  "#98C379"
bspc config urgent_border_color 	  "#E06C75"

bspc config split_ratio                   0.52
bspc config borderless_monocle            true
bspc config gapless_monocle               true

#bspc rule -a Screenkey manage=off

